version: "2"
services:
  web:
    image: loopback:latest
    ports:
    - "3000:3000"
    - "3001:3001"
    links:
      - mongodb
    depends_on:
    - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
